name: Deploy Static HTML to Azure Web App

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  deploy:
    runs-on: windows-latest  # Matches the OS setup for your Azure App Service

    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy static files directly to Azure Web App
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Shaving-private-ryan'  # Replace with the exact name of your Azure Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}